/*
 * This source file was generated by the Gradle 'init' task
 */
package minggu_4;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        AnimalApp classUnderTest = new AnimalApp();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
