/*
 * This source file was generated by the Gradle 'init' task
 */
package minggu_4;

public class AnimalApp {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Cat cat = new Cat("Bubu", 2, "Fish", Gender.MALE, Alive.ALIVE);
        Duck duck = new Duck("Dodo", 1, "Worm", Gender.FEMALE, Alive.ALIVE);
        Dog dog = new Dog("Skye", 3, "Meat", Gender.FEMALE, Alive.DEAD);
        Horse horse = new Horse("Jimney", 4, "Wheat", Gender.MALE, Alive.ALIVE);

        

        System.out.println(cat.printData());
        System.out.println();
        System.out.println(cat.move());
        System.out.println(cat.move(5));
        System.out.println();
        System.out.println(dog.printData());
        System.out.println();
        System.out.println(dog.move());
        System.out.println(dog.move(10));
        System.out.println();
        System.out.println(duck.printData());
        System.out.println();
        System.out.println(duck.move());
        System.out.println(duck.move(2));
        System.out.println();
        System.out.println(horse.printData());
        System.out.println();
        System.out.println(horse.move());
        System.out.println(horse.move(20));

    }
}
